import "@/app/globals.css";
import { UI, Providers, Sidebar } from "@/components";
import Header from "@/components/Header";
import { authOptions } from "@/lib/auth/options";
import ThemeProvider from "@/lib/contexts/Theme.context";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await getServerSession(authOptions);
	return (
		<ThemeProvider>
			<UI.HTML lang="en">
				<UI.Body
					className={`${roboto.className} bg-zinc-200 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-100 `}
				>
					<Providers>
						<Header />
						{children}
					</Providers>
				</UI.Body>
			</UI.HTML>
		</ThemeProvider>
	);
}
